### PR TITLE
Update v1.11.2

### PR DESCRIPTION
**Pull request by rxm7706**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by rxm7706** [comment]
@conda-forge-admin, please rerender

**Comment by rxm7706** [comment]
hi @mariusvniekerk - please review, the feedstock has been updated and all builds are passing now. Thanks and regards.

**Comment by rxm7706** [comment]
hi @mariusvniekerk @ocefpaf 

With avro-python3 depreciated - to get updated avro versions on conda-forge, we need this feedstock updated. could you please review and merge. I'm happy to help as a maintainer too, If needed. 

Thanks and Regards. 

Context
https://pypi.org/project/avro-python3/
'''
Deprecation Notice
[avro-python3](https://pypi.org/project/avro-python3/) is no longer maintained and is deprecated in favor of [avro](https://pypi.org/project/avro/). Avro is maintained and has full support for recent versions of Python.
'''

Legacy feedstock - https://github.com/conda-forge/avro-python3-feedstock/tree/main
Provides avro-python3 == 1.10.2 that points to https://pypi.org/project/avro-python3
While this feedstock points to the maintained https://pypi.org/project/avro/ and after this PR merge provides v1.11.2

**Comment by ocefpaf** [comment]
@mariusvniekerk is super busy these days and maybe it is a good idea to add yourself as a maintainer here too. Do you want to do it in this PR?

**Comment by rxm7706** [comment]
> @mariusvniekerk is super busy these days and maybe it is a good idea to add yourself as a maintainer here too. Do you want to do it in this PR?

Thanks @ocefpaf - Appreciate it . 
Added myself with a bot PR -  https://github.com/conda-forge/avro-feedstock/pull/21

**Pull request merged**
